name: Publish NPM Package
on:
  push:
    tags:
      - '*.*.*'

jobs:
  test-and-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-and-lint.yaml

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        ref: main
    - name: Setup node env
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16
        check-latest: true
    - name: Apply version to package.json
      run: |
        git fetch
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        npm version from-git -m "Apply version %s"
        git push
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        yarn install
        yarn prepare
        yarn publish
